onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_example_top/dut/hbramClk_pll_rstn_o
add wave -noupdate /tb_example_top/dut/hbramClk
add wave -noupdate /tb_example_top/dut/hbramClk90
add wave -noupdate /tb_example_top/dut/hbramClk_Cal
add wave -noupdate /tb_example_top/dut/hbramClk_pll_lock
add wave -noupdate /tb_example_top/dut/hbramClk_shift
add wave -noupdate /tb_example_top/dut/hbramClk_shift_ena
add wave -noupdate /tb_example_top/dut/hbramClk_shift_sel
add wave -noupdate /tb_example_top/dut/hdmi_pll_rstn_o
add wave -noupdate /tb_example_top/dut/hdmi_pixel_10x
add wave -noupdate /tb_example_top/dut/hdmi_pixel
add wave -noupdate /tb_example_top/dut/sensor_xclk_i
add wave -noupdate /tb_example_top/dut/sys_clk_i
add wave -noupdate /tb_example_top/dut/hdmi_pll_lock
add wave -noupdate /tb_example_top/dut/dsi_pll_rstn_o
add wave -noupdate /tb_example_top/dut/dsi_serclk_i
add wave -noupdate /tb_example_top/dut/dsi_txcclk_i
add wave -noupdate /tb_example_top/dut/dsi_byteclk_i
add wave -noupdate /tb_example_top/dut/dsi_fb_i
add wave -noupdate /tb_example_top/dut/dsi_pll_lock
add wave -noupdate /tb_example_top/dut/uart_rx_i
add wave -noupdate /tb_example_top/dut/uart_tx_o
add wave -noupdate /tb_example_top/dut/led_o
add wave -noupdate /tb_example_top/dut/spi_cs_o
add wave -noupdate /tb_example_top/dut/spi_cs_oe
add wave -noupdate /tb_example_top/dut/spi_sck_o
add wave -noupdate /tb_example_top/dut/spi_sck_oe
add wave -noupdate /tb_example_top/dut/spi_mosi_d0_i
add wave -noupdate /tb_example_top/dut/spi_mosi_d0_o
add wave -noupdate /tb_example_top/dut/spi_mosi_d0_oe
add wave -noupdate /tb_example_top/dut/spi_miso_d1_i
add wave -noupdate /tb_example_top/dut/spi_miso_d1_o
add wave -noupdate /tb_example_top/dut/spi_miso_d1_oe
add wave -noupdate /tb_example_top/dut/spi_wpn_d2_i
add wave -noupdate /tb_example_top/dut/spi_wpn_d2_o
add wave -noupdate /tb_example_top/dut/spi_wpn_d2_oe
add wave -noupdate /tb_example_top/dut/spi_holdn_d3_i
add wave -noupdate /tb_example_top/dut/spi_holdn_d3_o
add wave -noupdate /tb_example_top/dut/spi_holdn_d3_oe
add wave -noupdate /tb_example_top/dut/csi_trig_i
add wave -noupdate /tb_example_top/dut/csi_trig_o
add wave -noupdate /tb_example_top/dut/csi_trig_oe
add wave -noupdate /tb_example_top/dut/csi2_sda_i
add wave -noupdate /tb_example_top/dut/csi2_sda_o
add wave -noupdate /tb_example_top/dut/csi2_sda_oe
add wave -noupdate /tb_example_top/dut/csi_rxc_lp_p_i
add wave -noupdate /tb_example_top/dut/csi_rxc_lp_n_i
add wave -noupdate /tb_example_top/dut/csi_rxc_hs_en_o
add wave -noupdate /tb_example_top/dut/csi_rxc_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi_rxc_i
add wave -noupdate /tb_example_top/dut/csi_rxd0_rst_o
add wave -noupdate /tb_example_top/dut/csi_rxd0_hs_en_o
add wave -noupdate /tb_example_top/dut/csi_rxd0_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi_rxd0_lp_p_i
add wave -noupdate /tb_example_top/dut/csi_rxd0_lp_n_i
add wave -noupdate /tb_example_top/dut/csi_rxd0_hs_i
add wave -noupdate /tb_example_top/dut/csi_rxd1_rst_o
add wave -noupdate /tb_example_top/dut/csi_rxd1_hs_en_o
add wave -noupdate /tb_example_top/dut/csi_rxd1_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi_rxd1_lp_p_i
add wave -noupdate /tb_example_top/dut/csi_rxd1_lp_n_i
add wave -noupdate /tb_example_top/dut/csi_rxd1_hs_i
add wave -noupdate /tb_example_top/dut/csi_rxd2_rst_o
add wave -noupdate /tb_example_top/dut/csi_rxd2_hs_en_o
add wave -noupdate /tb_example_top/dut/csi_rxd2_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi_rxd2_lp_p_i
add wave -noupdate /tb_example_top/dut/csi_rxd2_lp_n_i
add wave -noupdate /tb_example_top/dut/csi_rxd2_hs_i
add wave -noupdate /tb_example_top/dut/csi_rxd3_rst_o
add wave -noupdate /tb_example_top/dut/csi_rxd3_hs_en_o
add wave -noupdate /tb_example_top/dut/csi_rxd3_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi_rxd3_lp_p_i
add wave -noupdate /tb_example_top/dut/csi_rxd3_lp_n_i
add wave -noupdate /tb_example_top/dut/csi_rxd3_hs_i
add wave -noupdate /tb_example_top/dut/csi2_rxc_lp_p_i
add wave -noupdate /tb_example_top/dut/csi2_rxc_lp_n_i
add wave -noupdate /tb_example_top/dut/csi2_rxc_hs_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxc_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxc_i
add wave -noupdate /tb_example_top/dut/csi2_rxd0_rst_o
add wave -noupdate /tb_example_top/dut/csi2_rxd0_hs_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxd0_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxd0_lp_p_i
add wave -noupdate /tb_example_top/dut/csi2_rxd0_lp_n_i
add wave -noupdate /tb_example_top/dut/csi2_rxd0_hs_i
add wave -noupdate /tb_example_top/dut/csi2_rxd1_rst_o
add wave -noupdate /tb_example_top/dut/csi2_rxd1_hs_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxd1_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxd1_lp_p_i
add wave -noupdate /tb_example_top/dut/csi2_rxd1_lp_n_i
add wave -noupdate /tb_example_top/dut/csi2_rxd1_hs_i
add wave -noupdate /tb_example_top/dut/csi2_rxd2_rst_o
add wave -noupdate /tb_example_top/dut/csi2_rxd2_hs_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxd2_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxd2_lp_p_i
add wave -noupdate /tb_example_top/dut/csi2_rxd2_lp_n_i
add wave -noupdate /tb_example_top/dut/csi2_rxd2_hs_i
add wave -noupdate /tb_example_top/dut/csi2_rxd3_rst_o
add wave -noupdate /tb_example_top/dut/csi2_rxd3_hs_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxd3_hs_term_en_o
add wave -noupdate /tb_example_top/dut/csi2_rxd3_lp_p_i
add wave -noupdate /tb_example_top/dut/csi2_rxd3_lp_n_i
add wave -noupdate /tb_example_top/dut/csi2_rxd3_hs_i
add wave -noupdate /tb_example_top/dut/dsi_pwm_o
add wave -noupdate /tb_example_top/dut/dsi_txc_rst_o
add wave -noupdate /tb_example_top/dut/dsi_txc_lp_p_oe
add wave -noupdate /tb_example_top/dut/dsi_txc_lp_p_o
add wave -noupdate /tb_example_top/dut/dsi_txc_lp_n_oe
add wave -noupdate /tb_example_top/dut/dsi_txc_lp_n_o
add wave -noupdate /tb_example_top/dut/dsi_txc_hs_oe
add wave -noupdate /tb_example_top/dut/dsi_txc_hs_o
add wave -noupdate /tb_example_top/dut/dsi_txd0_rst_o
add wave -noupdate /tb_example_top/dut/dsi_txd0_hs_oe
add wave -noupdate /tb_example_top/dut/dsi_txd0_hs_o
add wave -noupdate /tb_example_top/dut/dsi_txd0_lp_p_oe
add wave -noupdate /tb_example_top/dut/dsi_txd0_lp_p_o
add wave -noupdate /tb_example_top/dut/dsi_txd0_lp_n_oe
add wave -noupdate /tb_example_top/dut/dsi_txd0_lp_n_o
add wave -noupdate /tb_example_top/dut/dsi_txd1_rst_o
add wave -noupdate /tb_example_top/dut/dsi_txd1_lp_p_oe
add wave -noupdate /tb_example_top/dut/dsi_txd1_lp_p_o
add wave -noupdate /tb_example_top/dut/dsi_txd1_lp_n_oe
add wave -noupdate /tb_example_top/dut/dsi_txd1_lp_n_o
add wave -noupdate /tb_example_top/dut/dsi_txd1_hs_oe
add wave -noupdate /tb_example_top/dut/dsi_txd1_hs_o
add wave -noupdate /tb_example_top/dut/dsi_txd2_rst_o
add wave -noupdate /tb_example_top/dut/dsi_txd2_lp_p_oe
add wave -noupdate /tb_example_top/dut/dsi_txd2_lp_p_o
add wave -noupdate /tb_example_top/dut/dsi_txd2_lp_n_oe
add wave -noupdate /tb_example_top/dut/dsi_txd2_lp_n_o
add wave -noupdate /tb_example_top/dut/dsi_txd2_hs_oe
add wave -noupdate /tb_example_top/dut/dsi_txd2_hs_o
add wave -noupdate /tb_example_top/dut/dsi_txd3_rst_o
add wave -noupdate /tb_example_top/dut/dsi_txd3_lp_p_oe
add wave -noupdate /tb_example_top/dut/dsi_txd3_lp_p_o
add wave -noupdate /tb_example_top/dut/dsi_txd3_lp_n_oe
add wave -noupdate /tb_example_top/dut/dsi_txd3_lp_n_o
add wave -noupdate /tb_example_top/dut/dsi_txd3_hs_oe
add wave -noupdate /tb_example_top/dut/dsi_txd3_hs_o
add wave -noupdate /tb_example_top/dut/dsi_txd0_lp_p_i
add wave -noupdate /tb_example_top/dut/dsi_txd0_lp_n_i
add wave -noupdate /tb_example_top/dut/dsi_txd1_lp_p_i
add wave -noupdate /tb_example_top/dut/dsi_txd1_lp_n_i
add wave -noupdate /tb_example_top/dut/dsi_txd2_lp_p_i
add wave -noupdate /tb_example_top/dut/dsi_txd2_lp_n_i
add wave -noupdate /tb_example_top/dut/dsi_txd3_lp_p_i
add wave -noupdate /tb_example_top/dut/dsi_txd3_lp_n_i
add wave -noupdate /tb_example_top/dut/csi_tx_scl_i
add wave -noupdate /tb_example_top/dut/csi_tx_scl_o
add wave -noupdate /tb_example_top/dut/csi_tx_scl_oe
add wave -noupdate /tb_example_top/dut/csi_tx_sda_i
add wave -noupdate /tb_example_top/dut/csi_tx_sda_o
add wave -noupdate /tb_example_top/dut/csi_tx_sda_oe
add wave -noupdate /tb_example_top/dut/csi_txc_rst_o
add wave -noupdate /tb_example_top/dut/csi_txc_lp_p_oe
add wave -noupdate /tb_example_top/dut/csi_txc_lp_p_o
add wave -noupdate /tb_example_top/dut/csi_txc_lp_n_oe
add wave -noupdate /tb_example_top/dut/csi_txc_lp_n_o
add wave -noupdate /tb_example_top/dut/csi_txc_hs_oe
add wave -noupdate /tb_example_top/dut/csi_txc_hs_o
add wave -noupdate /tb_example_top/dut/csi_txd0_rst_o
add wave -noupdate /tb_example_top/dut/csi_txd0_hs_oe
add wave -noupdate /tb_example_top/dut/csi_txd0_hs_o
add wave -noupdate /tb_example_top/dut/csi_txd0_lp_p_oe
add wave -noupdate /tb_example_top/dut/csi_txd0_lp_p_o
add wave -noupdate /tb_example_top/dut/csi_txd0_lp_n_oe
add wave -noupdate /tb_example_top/dut/csi_txd0_lp_n_o
add wave -noupdate /tb_example_top/dut/csi_txd1_rst_o
add wave -noupdate /tb_example_top/dut/csi_txd1_lp_p_oe
add wave -noupdate /tb_example_top/dut/csi_txd1_lp_p_o
add wave -noupdate /tb_example_top/dut/csi_txd1_lp_n_oe
add wave -noupdate /tb_example_top/dut/csi_txd1_lp_n_o
add wave -noupdate /tb_example_top/dut/csi_txd1_hs_oe
add wave -noupdate /tb_example_top/dut/csi_txd1_hs_o
add wave -noupdate /tb_example_top/dut/csi_txd2_rst_o
add wave -noupdate /tb_example_top/dut/csi_txd2_lp_p_oe
add wave -noupdate /tb_example_top/dut/csi_txd2_lp_p_o
add wave -noupdate /tb_example_top/dut/csi_txd2_lp_n_oe
add wave -noupdate /tb_example_top/dut/csi_txd2_lp_n_o
add wave -noupdate /tb_example_top/dut/csi_txd2_hs_oe
add wave -noupdate /tb_example_top/dut/csi_txd2_hs_o
add wave -noupdate /tb_example_top/dut/csi_txd3_rst_o
add wave -noupdate /tb_example_top/dut/csi_txd3_lp_p_oe
add wave -noupdate /tb_example_top/dut/csi_txd3_lp_p_o
add wave -noupdate /tb_example_top/dut/csi_txd3_lp_n_oe
add wave -noupdate /tb_example_top/dut/csi_txd3_lp_n_o
add wave -noupdate /tb_example_top/dut/csi_txd3_hs_oe
add wave -noupdate /tb_example_top/dut/csi_txd3_hs_o
add wave -noupdate /tb_example_top/dut/csi_txd0_lp_p_i
add wave -noupdate /tb_example_top/dut/csi_txd0_lp_n_i
add wave -noupdate /tb_example_top/dut/csi_txd1_lp_p_i
add wave -noupdate /tb_example_top/dut/csi_txd1_lp_n_i
add wave -noupdate /tb_example_top/dut/csi_txd2_lp_p_i
add wave -noupdate /tb_example_top/dut/csi_txd2_lp_n_i
add wave -noupdate /tb_example_top/dut/csi_txd3_lp_p_i
add wave -noupdate /tb_example_top/dut/csi_txd3_lp_n_i
add wave -noupdate /tb_example_top/dut/hdmi_txc_oe
add wave -noupdate /tb_example_top/dut/hdmi_txd0_oe
add wave -noupdate /tb_example_top/dut/hdmi_txd1_oe
add wave -noupdate /tb_example_top/dut/hdmi_txd2_oe
add wave -noupdate /tb_example_top/dut/hdmi_txc_rst_o
add wave -noupdate /tb_example_top/dut/hdmi_txd0_rst_o
add wave -noupdate /tb_example_top/dut/hdmi_txd1_rst_o
add wave -noupdate /tb_example_top/dut/hdmi_txd2_rst_o
add wave -noupdate /tb_example_top/dut/hdmi_txc_o
add wave -noupdate /tb_example_top/dut/hdmi_txd0_o
add wave -noupdate /tb_example_top/dut/hdmi_txd1_o
add wave -noupdate /tb_example_top/dut/hdmi_txd2_o
add wave -noupdate /tb_example_top/dut/hbram_CK_P_HI
add wave -noupdate /tb_example_top/dut/hbram_CK_P_LO
add wave -noupdate /tb_example_top/dut/hbram_CK_N_HI
add wave -noupdate /tb_example_top/dut/hbram_CK_N_LO
add wave -noupdate /tb_example_top/dut/hbram_CS_N
add wave -noupdate /tb_example_top/dut/hbram_RST_N
add wave -noupdate /tb_example_top/dut/hbram_DQ_OUT_HI
add wave -noupdate /tb_example_top/dut/hbram_DQ_OUT_LO
add wave -noupdate /tb_example_top/dut/hbram_DQ_OE
add wave -noupdate /tb_example_top/dut/hbram_DQ_IN_HI
add wave -noupdate /tb_example_top/dut/hbram_DQ_IN_LO
add wave -noupdate /tb_example_top/dut/hbram_RWDS_OUT_HI
add wave -noupdate /tb_example_top/dut/hbram_RWDS_OUT_LO
add wave -noupdate /tb_example_top/dut/hbram_RWDS_OE
add wave -noupdate /tb_example_top/dut/hbram_RWDS_IN_HI
add wave -noupdate /tb_example_top/dut/hbram_RWDS_IN_LO
add wave -noupdate /tb_example_top/dut/w_syspll_lock_i
add wave -noupdate /tb_example_top/dut/w_pll_lock_i
add wave -noupdate /tb_example_top/dut/w_syspll_locked
add wave -noupdate /tb_example_top/dut/w_hbram_clk
add wave -noupdate /tb_example_top/dut/w_hbram_rst
add wave -noupdate /tb_example_top/dut/w_hbram_rstn
add wave -noupdate /tb_example_top/dut/w_pixel_clk
add wave -noupdate /tb_example_top/dut/w_pixel_rst
add wave -noupdate /tb_example_top/dut/w_pixel_rstn
add wave -noupdate /tb_example_top/dut/w_sys_clk
add wave -noupdate /tb_example_top/dut/w_sys_rst
add wave -noupdate /tb_example_top/dut/w_sys_rstn
add wave -noupdate /tb_example_top/dut/w_xclk
add wave -noupdate /tb_example_top/dut/w_xrst
add wave -noupdate /tb_example_top/dut/w_xrstn
add wave -noupdate /tb_example_top/dut/w_axi_clk
add wave -noupdate /tb_example_top/dut/w_axi_rst
add wave -noupdate /tb_example_top/dut/w_axi_rstn
add wave -noupdate /tb_example_top/dut/w_ustick
add wave -noupdate /tb_example_top/dut/w_mstick
add wave -noupdate /tb_example_top/dut/w_dev_index_o
add wave -noupdate /tb_example_top/dut/w_dev_cmd_o
add wave -noupdate /tb_example_top/dut/w_dev_wdata_o
add wave -noupdate /tb_example_top/dut/w_dev_wvalid_o
add wave -noupdate /tb_example_top/dut/w_dev_rvalid_o
add wave -noupdate /tb_example_top/dut/w_dev_rdata_i
add wave -noupdate /tb_example_top/dut/w_scl_o
add wave -noupdate /tb_example_top/dut/w_scl_oe
add wave -noupdate /tb_example_top/dut/w_sda_o
add wave -noupdate /tb_example_top/dut/w_sda_oe
add wave -noupdate /tb_example_top/dut/w_sda_i
add wave -noupdate /tb_example_top/dut/w_spi_ssn_o
add wave -noupdate /tb_example_top/dut/w_spi_sck_o
add wave -noupdate /tb_example_top/dut/w_spi_data_o
add wave -noupdate /tb_example_top/dut/w_spi_data_oe
add wave -noupdate /tb_example_top/dut/w_spi_data_i
add wave -noupdate /tb_example_top/dut/w_soc_runz
add wave -noupdate /tb_example_top/dut/r_flash_en
add wave -noupdate /tb_example_top/dut/sc2210_i2c_config_index
add wave -noupdate /tb_example_top/dut/sc2210_i2c_config_data
add wave -noupdate /tb_example_top/dut/sc2210_i2c_config_size
add wave -noupdate /tb_example_top/dut/sc2210_i2c_config_done
add wave -noupdate /tb_example_top/dut/w_i2c0_scl_o
add wave -noupdate /tb_example_top/dut/w_i2c0_sda_i
add wave -noupdate /tb_example_top/dut/w_i2c0_sda_o
add wave -noupdate /tb_example_top/dut/w_i2c0_sda_oe
add wave -noupdate /tb_example_top/dut/csi_scl_oe
add wave -noupdate /tb_example_top/dut/r_dsi_pwm
add wave -noupdate /tb_example_top/dut/rc_pwm
add wave -noupdate /tb_example_top/dut/r_dsi_pwm_o
add wave -noupdate /tb_example_top/dut/w_hbram_ui_clk
add wave -noupdate /tb_example_top/dut/w_hbram_ui_rst
add wave -noupdate /tb_example_top/dut/w_hbram_ui_areset
add wave -noupdate /tb_example_top/dut/w_hbram_ui_aresetn
add wave -noupdate /tb_example_top/dut/w_hbram_awid
add wave -noupdate /tb_example_top/dut/w_hbram_awaddr
add wave -noupdate /tb_example_top/dut/w_hbram_awlen
add wave -noupdate /tb_example_top/dut/w_hbram_awvalid
add wave -noupdate /tb_example_top/dut/w_hbram_awready
add wave -noupdate /tb_example_top/dut/w_hbram_wid
add wave -noupdate /tb_example_top/dut/w_hbram_wdata
add wave -noupdate /tb_example_top/dut/w_hbram_wstrb
add wave -noupdate /tb_example_top/dut/w_hbram_wlast
add wave -noupdate /tb_example_top/dut/w_hbram_wvalid
add wave -noupdate /tb_example_top/dut/w_hbram_wready
add wave -noupdate /tb_example_top/dut/w_hbram_bid
add wave -noupdate /tb_example_top/dut/w_hbram_bresp
add wave -noupdate /tb_example_top/dut/w_hbram_bvalid
add wave -noupdate /tb_example_top/dut/w_hbram_bready
add wave -noupdate /tb_example_top/dut/w_hbram_arid
add wave -noupdate /tb_example_top/dut/w_hbram_araddr
add wave -noupdate /tb_example_top/dut/w_hbram_arlen
add wave -noupdate /tb_example_top/dut/w_hbram_arvalid
add wave -noupdate /tb_example_top/dut/w_hbram_arready
add wave -noupdate /tb_example_top/dut/w_hbram_rid
add wave -noupdate /tb_example_top/dut/w_hbram_rdata
add wave -noupdate /tb_example_top/dut/w_hbram_rlast
add wave -noupdate /tb_example_top/dut/w_hbram_rvalid
add wave -noupdate /tb_example_top/dut/w_hbram_rready
add wave -noupdate /tb_example_top/dut/w_hbram_rresp
add wave -noupdate /tb_example_top/dut/w_hbram_aid
add wave -noupdate /tb_example_top/dut/w_hbram_aaddr
add wave -noupdate /tb_example_top/dut/w_hbram_alen
add wave -noupdate /tb_example_top/dut/w_hbram_asize
add wave -noupdate /tb_example_top/dut/w_hbram_aburst
add wave -noupdate /tb_example_top/dut/w_hbram_alock
add wave -noupdate /tb_example_top/dut/w_hbram_avalid
add wave -noupdate /tb_example_top/dut/w_hbram_aready
add wave -noupdate /tb_example_top/dut/w_hbram_atype
add wave -noupdate /tb_example_top/dut/w_hbram_cal_pass
add wave -noupdate /tb_example_top/dut/w_hbram_cal_done
add wave -noupdate /tb_example_top/dut/w_hbram_cal_dbg
add wave -noupdate /tb_example_top/dut/w_csi_rx_clk
add wave -noupdate /tb_example_top/dut/w_csi_rx_vsync0
add wave -noupdate /tb_example_top/dut/w_csi_rx_hsync0
add wave -noupdate /tb_example_top/dut/w_csi_rx_dvalid
add wave -noupdate /tb_example_top/dut/w_csi_rx_data
add wave -noupdate /tb_example_top/dut/w_csi_rx_data_rel_raw
add wave -noupdate /tb_example_top/dut/w_csi_axi_rdata
add wave -noupdate /tb_example_top/dut/w_csi_axi_awready
add wave -noupdate /tb_example_top/dut/w_csi_axi_wready
add wave -noupdate /tb_example_top/dut/w_csi_axi_arready
add wave -noupdate /tb_example_top/dut/w_csi_axi_rvalid
add wave -noupdate /tb_example_top/dut/r_reset_pixen_n
add wave -noupdate /tb_example_top/dut/r_csi_rx_vsync0_i
add wave -noupdate /tb_example_top/dut/csi_rxd3_fifo_rd_o
add wave -noupdate /tb_example_top/dut/csi_rxd2_fifo_rd_o
add wave -noupdate /tb_example_top/dut/csi_rxd1_fifo_rd_o
add wave -noupdate /tb_example_top/dut/csi_rxd0_fifo_rd_o
add wave -noupdate /tb_example_top/dut/csi_rxd3_fifo_empty_i
add wave -noupdate /tb_example_top/dut/csi_rxd2_fifo_empty_i
add wave -noupdate /tb_example_top/dut/csi_rxd1_fifo_empty_i
add wave -noupdate /tb_example_top/dut/csi_rxd0_fifo_empty_i
add wave -noupdate /tb_example_top/dut/r_axi_addr
add wave -noupdate /tb_example_top/dut/r_axi_sel
add wave -noupdate /tb_example_top/dut/CSI_AXILITE_ID
add wave -noupdate /tb_example_top/dut/r_axi_awvalid
add wave -noupdate /tb_example_top/dut/r_axi_wvalid
add wave -noupdate /tb_example_top/dut/r_axi_wdata
add wave -noupdate /tb_example_top/dut/r_axi_arvalid
add wave -noupdate /tb_example_top/dut/w_sim_fv
add wave -noupdate /tb_example_top/dut/w_sim_lv
add wave -noupdate /tb_example_top/dut/w_sim_de
add wave -noupdate /tb_example_top/dut/r_sim_data
add wave -noupdate /tb_example_top/dut/cmos_frame_vsync
add wave -noupdate /tb_example_top/dut/cmos_frame_href
add wave -noupdate /tb_example_top/dut/cmos_frame_Gray
add wave -noupdate /tb_example_top/dut/r_vsync_i
add wave -noupdate /tb_example_top/dut/rc_vsync
add wave -noupdate /tb_example_top/dut/lcd_de
add wave -noupdate /tb_example_top/dut/lcd_hs
add wave -noupdate /tb_example_top/dut/lcd_vs
add wave -noupdate /tb_example_top/dut/lcd_request
add wave -noupdate /tb_example_top/dut/lcd_red
add wave -noupdate /tb_example_top/dut/lcd_red2
add wave -noupdate /tb_example_top/dut/lcd_green
add wave -noupdate /tb_example_top/dut/lcd_green2
add wave -noupdate /tb_example_top/dut/lcd_blue
add wave -noupdate /tb_example_top/dut/lcd_blue2
add wave -noupdate /tb_example_top/dut/lcd_data
add wave -noupdate /tb_example_top/dut/w_wframe_vsync
add wave -noupdate /tb_example_top/dut/w_axi_tp
add wave -noupdate /tb_example_top/dut/w_rgb_vsync
add wave -noupdate /tb_example_top/dut/w_rgb_href
add wave -noupdate /tb_example_top/dut/w_rgb_r
add wave -noupdate /tb_example_top/dut/w_rgb_g
add wave -noupdate /tb_example_top/dut/w_rgb_b
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_clk
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_reset
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_awid
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_awaddr
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_awlen
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_awsize
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_awburst
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_awlock
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_awcache
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_awprot
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_awqos
add wave -noupdate -itemcolor Yellow /tb_example_top/dut/u_axi4_ctrl/axi_awvalid
add wave -noupdate -itemcolor Yellow /tb_example_top/dut/u_axi4_ctrl/axi_awready
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_wdata
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_wstrb
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_wlast
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_wvalid
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_wready
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_bid
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_bresp
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_bvalid
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_bready
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arid
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_araddr
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arlen
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arsize
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arburst
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arlock
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arcache
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arprot
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arqos
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arvalid
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_arready
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_rid
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_rdata
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_rresp
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_rlast
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_rvalid
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/axi_rready
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/wframe_pclk
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/wframe_vsync
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/wframe_data_en
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/wframe_data
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rframe_pclk
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rframe_vsync
add wave -noupdate -itemcolor Red /tb_example_top/dut/u_axi4_ctrl/rframe_data_valid
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rframe_data_en
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rframe_data
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rframe_idle
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/tp_o
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rc_wframe_index
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rc_rframe_index
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_wframe_index_p1
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_wframe_index_next
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/r_wframe_index_last
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/r_wframe_inc
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/r_rframe_inc
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_wfifo_pempty
add wave -noupdate -itemcolor Red /tb_example_top/dut/u_axi4_ctrl/w_wfifo_empty
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_wfifo_ren
add wave -noupdate -radix hexadecimal /tb_example_top/dut/u_axi4_ctrl/w_wfifo_rdata
add wave -noupdate -itemcolor Yellow /tb_example_top/dut/u_axi4_ctrl/rs_w
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_w_idle
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_w_wdata
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_w_winc
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_w_eof
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_w_wend
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rc_w_ptr
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rc_w_eof
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/r_w_rst
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rc_burst
add wave -noupdate -itemcolor Red /tb_example_top/dut/u_axi4_ctrl/r_wframe_sync
add wave -noupdate -itemcolor Red /tb_example_top/dut/u_axi4_ctrl/r_weof_pending
add wave -noupdate -radix hexadecimal /tb_example_top/dut/u_axi4_ctrl/r_wfifo_wdata
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_wfifo_wdata
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rc_wfifo_we
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rc_r_ptr
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_rfifo_wfull
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/r_r_eof
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rs_r
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_r_idle
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_r_rbufchk
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_r_rreq
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_r_rinc
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_r_wait
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/ws_r_chk
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/r_rframe_vsync
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_rfifo_rst
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_rfifo_aempty
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_rfifo_empty
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_rframe_data_en_fifo
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_rframe_data_en_load
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_rframe_data_gen
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_rframe_data_en
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/rc_rfifo_rd
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/w_rfifo_rend
add wave -noupdate /tb_example_top/dut/u_axi4_ctrl/r_rframe_data_gen
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/aclk_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/arst_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/awid_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/awaddr_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/awlen_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/awvalid_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/awready_o
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/arid_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/araddr_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/arlen_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/arvalid_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/arready_o
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/aid_o
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/aaddr_o
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/alen_o
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/atype_o
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/avalid_o
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/aready_i
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/rs_req
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/ws_req_idle
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/ws_req_bridge
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/ws_req_inc
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/r_reqtype
add wave -noupdate /tb_example_top/dut/axi4_awar_mux/r_reqen
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {31006429 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 325
configure wave -valuecolwidth 219
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {29587395 ps} {45435934 ps}
